const fs = require('fs');

// A 1x1 valid JPEG in base64
const b64 = '/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////wgALCAABAAEBAREA/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxA=';

// Wait, the above base64 was the one Cloudinary rejected as invalid resource!
// Let's use a standard 2x2 valid JPEG base64
const validB64 = '/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wgARCAACAAIDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EABQBAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhADEAAAAQJ//8QAFBABAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8QKw//xAAUEQEAAAAAAAAAAAAAAAAAAAAQ/9oACAECAQE/EEf/xAAUEQEAAAAAAAAAAAAAAAAAAAAQ/9oACAEDAQE/EEf/xAAUEAEAAAAAAAAAAAAAAAAAAAAQ/9oACAEBAAE/EA3/2Q==';

fs.writeFileSync('dummy.jpg', Buffer.from(validB64, 'base64'));
